# Generated by Django 3.0.5 on 2020-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='books',
            field=models.TextField(default='Updating soon', verbose_name='Books'),
        ),
        migrations.AddField(
            model_name='subject',
            name='docs',
            field=models.TextField(default='Updating soon', verbose_name='Documentaries'),
        ),
        migrations.AddField(
            model_name='subject',
            name='fb_pages',
            field=models.TextField(default='Updating soon', verbose_name='Facebook Pages'),
        ),
        migrations.AddField(
            model_name='subject',
            name='insta_pages',
            field=models.TextField(default='Updating soon', verbose_name='Instagram Pages'),
        ),
        migrations.AddField(
            model_name='subject',
            name='movies',
            field=models.TextField(default='Updating soon', verbose_name='Movies'),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='subject',
            name='websites',
            field=models.TextField(default='Updating soon', verbose_name='Websites'),
        ),
        migrations.AddField(
            model_name='subject',
            name='yt_channels',
            field=models.TextField(default='Updating soon', verbose_name='Youtube Channels'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
